### ISSUE TITLE
Can header row be removed?

### ISSUE THREAD

**Issue by coolcalmcollected22** [tedsmith/NSRL-Stripper#1]
I just wanted to say this is a great tool and has been helpful. Keep up the good work. Is it possible not to have a header row? Just the hashes alone?

Thanks!

**Comment by tedsmith** [comment]
Thanks very much. You’re the first person to say so!! 

Re the header...I suppose but it’s easier for the user to just open the output and delete line 1.

**Comment by coolcalmcollected22** [comment]
Oh yeah, it is easy to delete the line assuming that the list isn't too large. I have done that. But some lists can get too large and even programs like notepad++ can't open it and it will take programmatic action to remove it. With it gone all the tools I am aware will ingest it while a few may not like that first line or may require a workaround so I thought I would mention it.

**Comment by tedsmith** [comment]
Fair point. I recall that myself actually (notepad++ even struggling) which was actually why I made the program in the first place!!! I’ll add it to my to do list. Thanks

**Comment by tedsmith** [comment]
Your suggestions is implemented into v1.1
